import { describe, expect, it, vi } from "vitest";
import { processArchiveMonth, type ArchiveOperationDependencies } from "@/lib/archive-operation";
import type { ArchiveInputItem, MonthlyArchive } from "@/types/archive";

const archive: MonthlyArchive = { version: 1, month: "2026-07", periodStart: "2026-07-01", periodEnd: "2026-07-31", generatedAt: "2026-08-01T10:00:00Z", model: "fixture", wirtschaft: { id: "id", category: "wirtschaft", title: "Titel", teaser: "Teaser", developmentLines: ["A","B","C"], managementSummary: ["A","B","C"], briefingText: "Text", whyImportant: "Wichtig", concreteImpact: "Folge", uncertainty: "low", sources: [{ articleId: "a", name: "A", url: "https://example.com", publishedAt: "2026-07-01T00:00:00Z" }] } };
function fixtures(): ArchiveInputItem[] { const topics = ["Zollabkommen Europa", "Leitzinsentscheidung Zentralbank", "Chipinvestition Sachsen", "Ölmarkt Förderquote", "Industrieauftrag Maschinenbau", "Inflationsdaten Eurozone"]; return Array.from({ length: 6 }, (_, i) => ({ id: `i${i}`, category: "wirtschaft", title: topics[i], teaser: `Teaser ${i}`, summary: "Text", whyImportant: "Wichtig", concreteImpact: "Folge", uncertainty: "low", sources: [{ articleId: `a${i}`, name: ["A","B","C"][i%3], url: `https://example.com/${i}`, publishedAt: "2026-07-10T00:00:00Z" }] })); }
function deps(overrides: Record<string, unknown> = {}) {
  const state = { version: 1 as const, months: {} };
  const storage = { loadArchiveRunState: vi.fn(async () => state), saveArchiveRunState: vi.fn(), loadArchiveMonth: vi.fn(async () => null), listArchiveInputs: vi.fn(async () => [{ version: 1 as const, date: "2026-07-10", collectedAt: "2026-07-10T10:00:00Z", categories: { wirtschaft: fixtures(), politik: [] } }]), saveArchiveMonth: vi.fn(), loadArchiveIndex: vi.fn(async () => ({ version: 1 as const, months: [] })), saveArchiveIndex: vi.fn(), cleanupArchiveInputs: vi.fn(), ...overrides };
  const generate = vi.fn(async () => archive); return { dependencies: { storage, generate } as unknown as ArchiveOperationDependencies, storage, generate };
}
describe("archive operation", () => {
  it("skips the first incomplete collection month", async () => { const d = deps(); expect((await processArchiveMonth(new Date("2026-08-01T10:00:00Z"), "2026-08", d.dependencies)).status).toBe("incomplete"); expect(d.generate).not.toHaveBeenCalled(); });
  it("marks an unqualified empty result processed without model call", async () => { const d = deps({ listArchiveInputs: vi.fn(async () => []) }); expect((await processArchiveMonth(new Date("2026-08-01T10:00:00Z"), "2026-07", d.dependencies)).status).toBe("empty"); expect(d.generate).not.toHaveBeenCalled(); expect(d.storage.saveArchiveRunState).toHaveBeenCalledTimes(2); });
  it("repairs an index for an existing archive without model call", async () => { const d = deps({ loadArchiveMonth: vi.fn(async () => archive) }); expect((await processArchiveMonth(new Date("2026-08-01T10:00:00Z"), "2026-07", d.dependencies)).status).toBe("existing"); expect(d.generate).not.toHaveBeenCalled(); expect(d.storage.saveArchiveIndex).toHaveBeenCalled(); });
  it("counts before generation and validates/saves as one result", async () => { const d = deps(); expect((await processArchiveMonth(new Date("2026-08-01T10:00:00Z"), "2026-07", d.dependencies)).status).toBe("generated"); expect(d.storage.saveArchiveRunState.mock.invocationCallOrder[0]).toBeLessThan(d.generate.mock.invocationCallOrder[0]); expect(d.storage.saveArchiveMonth).toHaveBeenCalledWith(archive); });
  it("keeps cleanup failures non-blocking", async () => { const d = deps({ cleanupArchiveInputs: vi.fn(async () => { throw new Error("cleanup"); }) }); await expect(processArchiveMonth(new Date("2026-08-01T10:00:00Z"), "2026-07", d.dependencies)).resolves.toEqual({ status: "generated" }); });
});
